config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :favorites
  resources :sessions
  
  root to: "pictures#new"
  resources :pictures do
      collection do
        post :confirm
      end
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine,at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
    validates :comment,length:{maximum:140},presence: true
    validates :picture,presence: true
    
    belongs_to :user
    has_many :favorites,dependent: :destroy
    has_many :users,through: :favorites
    mount_uploader :picture,PictureUploader
    
    
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    has_many :pictures
    has_many :pictures,through: :favorites
    has_many :favorites,dependent: :destroy
    
    validates :name,presence: true,length:{maximum: 30}
    validates :email,presence: true,length:{maximum: 100},uniqueness: true,format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    validates :password,presence: true,length:{in: 6..100}
    before_save {email.downcase!}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def index
        @user = current_user
        @favorites = @user.favorites.all
    end
    
    def create
        favorite = current_user.favorites.create(picture_id: params[:picture_id])
        redirect_to pictures_path,notice:"#{favorite.picture.user.name}さんのピクチャーをいいねしました"
    end
    
    def destroy
        favorite = current_user.favorites.find(params[:id])
        favorite.destroy
        redirect_to pictures_path,notice:"#{favorite.picture.user.name}さんのピクチャーをいいね解除しました"
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    before_action :plz_login
    before_action :set_picture,only:[:show,:edit,:update,:destroy]
    
    def index
        @pictures = Picture.all
    end
    
    def new
        if params[:back]
            @picture = Picture.new(picture_params)
        else
            @picture = Picture.new
        end
    end
    
    def show
        @favorite = current_user.favorites.find_by(picture_id: @picture.id)
    end
    
    
    def confirm
        @picture = Picture.new(picture_params)
        @picture.user_id = current_user.id
        render 'new' if @picture.invalid?
    end
    
    def create
        @picture = Picture.new(picture_params)
        @picture.user_id = current_user.id
        @picture.picture.retrieve_from_cache! params[:cache][:picture]
        if @picture.save
            PostConfirmMailer.post_confirm_mail(@picture).deliver
            redirect_to pictures_path,notice:"投稿しました"
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @picture.update(picture_params)
            redirect_to pictures_path,notice:"更新しました"
        else
            render 'edit'
        end
    end
    
    def destroy
        @picture.destroy
        redirect_to pictures_path,notice:"削除しました"
    end
    
    private
    def plz_login
        unless logged_in? then
            redirect_to new_session_path
        end
    end
    
    def picture_params
        params.require(:picture).permit(:comment,:picture,:picture_cache)
    end
    
    def set_picture
        @picture = Picture.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user,only:[:show]
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user.id)
        else
            render 'new'
        end
    end
    
    def show
    end
    
    private
    def user_params
        params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end
    
    def set_user
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
    def new_or_edit
      if action_name == 'new' ||action_name == 'confirm'
        confirm_pictures_path
      elsif action_name == 'edit'
        picture_path
      end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !current_user.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h1>お気に入り一覧</h1>

<% @favorites.each do |fav| %>
  <% writer = User.find(fav.picture.user_id) %>
  <div class="content-wrapper">
    <p><strong>name:</strong><%= writer.name %></p>
    <p><strong>comment:</strong><%= fav.picture.comment %></p>
    <div class="image-wrapper">
      <%= image_tag (fav.picture.picture_url) %>
      <%= link_to "お気に入り解除する",favorite_path(fav.id),method: :delete %>
    </div>
  </div>
<% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <h1>Instaclone</h1>
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
      <%= link_to "New Post",new_picture_path %>
      <%= link_to "Index",pictures_path %>
      <%= link_to "Favorites",favorites_path %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture,local: true,url: new_or_edit) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
        <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
        <ul>
            <% @picture.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
  <% end %>
  <table>
    <tr>
      <div class="picture_comment">
        <td><%= form.label :comment %></td>
        <td><%= form.text_field :comment %></td>
      </div>
    </tr>
    <tr>
      <div class="field">
        <td><%= form.label :picture %></td>
        <td><%= form.file_field :picture, id: :picture_picture %></td>
        <%= form.hidden_field :picture_cache %>
      </div>
    </tr>
  </table>
  <%= form.submit %>
<% end %>

<%= link_to '一覧に戻る',pictures_path %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で送信します</h3>
<%= form_with(model: @picture,url: pictures_path,local: true) do |form| %>
<div class="content-wrapper">
  <% if @picture.comment.present? %>
    <%= form.hidden_field :comment %>
    <p><strong>comment:</strong><%= @picture.comment %></p>
  <% end %>
    <%= image_tag(@picture.picture.url) %>
    <%= hidden_field_tag :"cache[picture]",@picture.picture.cache_name %>
</div>
    <%= form.submit "登録する"%>
<% end %>

<%= form_with(model: @picture,url: new_picture_path,local: true,method: 'get') do |form|%>
  <%= form.hidden_field :picture %>
  <%= hidden_field :"cache[picture]",@picture.picture.cache_name %>
  <%= form.submit '戻る',name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h1>edit post</h1>

<%= render 'form' %>

app/views/pictures/index.html.erb
<h1>Index</h1>
<% @pictures.each do |pic| %>
  <div class="content-wrapper">
    <p class="name"><strong>user:</strong> <%= pic.user.name %></p>
    <div class="image-wrapper">
      <p><strong>comment:</strong> <%= pic.comment %></p>
      <%= image_tag(pic.picture) %>
    </div>
    <%= link_to "詳細へ",picture_path(pic.id) %>
    <% if pic.user == current_user %>
      <%= link_to "edit",edit_picture_path(pic.id) %>
      <%= link_to "delete",picture_path(pic.id),method: :delete,data:{confirm:"本当に削除していいですか？"} %>
  　<% end %>
　</div>
<% end %>

app/views/pictures/new.html.erb
<h1>new post</h1>

<%= render 'form' %>

app/views/pictures/show.html.erb
<div class="content-wrapper">
  <h4><strong>comment:</strong><%= @picture.comment %></h4>
  <h4><%= image_tag(@picture.picture) %></h4>
  <%= link_to "一覧へ",pictures_path %>
</div>
<% unless @picture.user == current_user %>
  <% if @favorite.present? %>
    <%= link_to "お気に入り解除します",favorite_path(picture_id: @picture.id),method: :delete %>
  <% else %>
    <%= link_to "お気に入りする",favorites_path(picture_id: @picture.id),method: :post %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>email:<%= @user.email %></p>